### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by licode** [scikit-beam/scikit-beam#337]
From the conference this week, I find lots of people are interested in using our package. However, some of them are windows users only. Any plan that we can move one step forward to windows? @tacaswell @ericdill @danielballan ?

**Comment by danielballan** [comment]
I'm not sure yet how hard that will be. Some functionality will be easy (anything that only needs pure Python code) but some might be hard/impossible (xraylib).

**Comment by danielballan** [comment]
We should at least *attempt* this before the end of the year.

**Comment by chrisvam** [comment]
Since pip is include with python 2.7.9 and 3.4, is it is possible that
"pip install -r requirements.txt -r optional-requirements.txt scikit-xray"
would work on windows for those versions of python?

I know we wouldn't get xraylib, but my understanding is that most of
rest of scikit-xray would be functional.

chris

**Comment by danielballan** [comment]
@chrisvam pip works well with Python-only projects, but tends to be problematic when projects include C or Fortran code, as scikit-xray does. If your system is not configured properly, the setup.py will fail because of [this setting](https://github.com/scikit-xray/scikit-xray/blob/master/setup.py#L27).

Conda was developed to solve exactly this problem. We can aim to build binary conda packages for Windows so that our users don't have to worry about the compiler details; or, in the short term, we could package the C dependencies in separate package, make it an optional dependency of scikit-xray, and keep the core package in pure Python.

By all means, give pip a try and please let us know how it goes.

**Comment by ericdill** [comment]
@licode  The biggest blocker to getting a windows binary for scikit-xray is going to be getting a conda recipe for xraylib so that we can reliably compile it for windows.

**Comment by ericdill** [comment]
I have a demonstration of using docker on mac to install pyXRF (which requires xraylib), running the GUI inside of the docker container and forwarding the GUI to the host mac laptop. That docker file and associated instructions is located [here] (https://github.com/ericdill/pyxrf-docker).  I would imagine that it would be possible to docker on windows when we need to use any libraries that have dependencies we have not yet been able to compile on windows. 

Thoughts?

**Comment by danielballan** [comment]
Sound reasonable to me, though to be honest my early experiences as a docker user on OSX scared me away at first. Not sure how Windows users feel about Docker as a stop-gap. It would be interested to hear from some....

**Comment by dgursoy** [comment]
Is it only xraylib causing the issue?

**Comment by ericdill** [comment]
I think so

**Comment by licode** [comment]
see conda-forge https://anaconda.org/conda-forge/scikit-beam/files
