### ISSUE TITLE
Fix test suite errors with lmfit >0.8.3

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#448]
If you run the test suite with lmfit > 0.8.3, a number of errors are spit out. Perhaps @licode could investigate why this is happening and fix it so we can use new lmfit versions

**Comment by licode** [comment]
Sure. This requires some efforts. Due to new release of scipy, more updates are expected on lmfit I guess.

**Comment by danielballan** [comment]
It is now impossible to install scikit-beam and larch on the same system because requires modern lmfit. NSLS-II's scikit-beam conda package will work around this by unpinning lmfit and allowing the user to decide whether to accept:

* broken skbeam xrf code in order to use larch / modern lmfit
* working skbeam xrf code but no larch support

This needs to be addressed.

**Comment by danielballan** [comment]
Bump.

**Comment by mrakitin** [comment]
This issue seems to be resolved by @dmgav via #547.
